### ISSUE TITLE
Single package for both web and nodejs

### ISSUE THREAD

**Issue by mateuszmlc** [spacetimehq/spacetime-parser#5]
wasm-pack has separate web, bundler and nodejs targets. The client library is used from both nodejs and web (social demo).
I tried to dynamically load either bundler or nodejs depending on the environment (bundler for webpack, nodejs otherwise), but webpack still tries to process the nodejs files, which fails. I don't think there's a way to make webpack ignore them.
The approach I'm trying now is to use `bundler` with node, but we will need to use ESM modules and pass `--experimental-wasm-modules` to `node`.

**Comment by calummoore** [comment]
If we need to, we can create a separate repo for node and browser

**Comment by mateuszmlc** [comment]
I was trying to avoid that, but yes we could make separate packages for them, would we also split the client into @spacetimexyz/client-web, @spacetimexyz/client-node?

**Comment by calummoore** [comment]
I think I would go with `@spacetimexyz/browser` and `@spacetimexyz/node`

I would prefer not to have separate modules too, the problem with using esm is it makes it difficult for people not using esm. The other option is to have one library and have a path to the relevant code `@spacetimexyz/client/browser` and `@spacetimexyz/client/node`

**Comment by mateuszmlc** [comment]
I like that option with a path, should I start working on that? I think we will need a bundler, I would go with webpack unless you prefer something else

**Comment by calummoore** [comment]
Yes please. Webpack is fine. 👍

**Comment by mateuszmlc** [comment]
I will be done with this by the end of the day, it's pretty tricky to set up. Instead of a browser target we will have a bundler target, the wasm bindings files have to be processed at the very end (not in parser's or client's webpack build but website's webpack, otherwise it processes it multiple times and breaks it), it will probably need changes to the default react webpack config (`experiments.asyncWebAssembly`).

The setup could be made simpler by inlining the .wasm file as a base64 string in javascript, might try that today

**Comment by mateuszmlc** [comment]
nvm, went with the web/node split approach

**Comment by calummoore** [comment]
@mateuszmlc did you manage to get this to work then with using a single `@spacetimexyz/parser`? I see in the `@spacetimexyz/client` we just import it directly.

**Comment by mateuszmlc** [comment]
> @mateuszmlc did you manage to get this to work then with using a single `@spacetimexyz/parser`? I see in the `@spacetimexyz/client` we just import it directly.

Yes, it's a single package. `@spacetimexyz/parser/node` for node, `@spacetimexyz/parser/web` for web, in webpack and jest config we alias `@spacetimexyz/parser` imports to either /node or /web

**Comment by calummoore** [comment]
Ok, and then the same for the client lib `@spacetimexyz/client/node` and  `@spacetimexyz/client/web`

**Comment by calummoore** [comment]
Can we default `@spacetimexyz/client` -> `@spacetimexyz/client/web`?

**Comment by mateuszmlc** [comment]
> Ok, and then the same for the client lib `@spacetimexyz/client/node` and `@spacetimexyz/client/web`?

Yes

> Can we default `@spacetimexyz/client` -> `@spacetimexyz/client/web`?

Will do, I think that only requires changing `main` in package.json
